const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const sandbox = vm.createContext({ window: { Unterrichtsassistent: { features: { evaluation: {} } } }, Date, Map, Set });
for (const file of ['src/shared/html.js', 'src/domain/models.js', 'src/domain/factories.js', 'src/features/evaluation/studentOverview.js']) vm.runInContext(fs.readFileSync(path.join(__dirname, '..', file), 'utf8'), sandbox, { filename: file });
const ns = sandbox.window.Unterrichtsassistent;
const feature = ns.features.evaluation.studentOverview;
const quality = (type, raw = {}, extra = {}, snapshot = {}) => feature.qualityOf({ type, raw, ...extra }, snapshot);
const plain = value => JSON.parse(JSON.stringify(value));

test('normalizes performance scales; missing values and nonperformance data never become zero', () => {
  assert.equal(quality('assessment', { afb1: 2, afb2: '', afb3: null }), 4);
  assert.equal(quality('assessment', { overallImpression: 0 }), 2);
  assert.equal(quality('assessment', { afb1: '--', afb2: '+' }), 1.5);
  assert.equal(quality('assessment', { score: 0, maxScore: 20 }), 0);
  assert.equal(quality('assessment', { score: 15, maxScore: 20, afb1: '--', afb2: '--', afb3: '--' }), 3);
  assert.equal(quality('assessment', { note: 'Text', workBehavior: 'd' }), null);
  assert.equal(quality('assessment', new ns.domain.Assessment({ note: 'Text' })), null);
  assert.equal(quality('mathObservation', { processQuality: 0, mathObservationQualityScale: '0-4' }), 0);
  assert.equal(quality('mathObservation', { processQuality: 0 }), 2);
  assert.equal(quality('mathObservation', { competencyQualities: [{ quality: '' }, { quality: 4 }], mathObservationQualityScale: '0-4' }), 4);
  assert.equal(quality('mathObservation', new ns.domain.MathObservationRecord({ note: 'Nur eine Notiz' })), null);
  for (const type of ['attendance','homework','warning','knowledgeGap','grade','comment']) assert.equal(quality(type, { grade: 1, quality: 4 }), null);
  assert.equal(quality('completedEvaluation', {}, { percent: null }), null);
  assert.equal(quality('completedEvaluation', {}, { percent: 0 }), 0);
  assert.equal(quality('completedEvaluation', {}, { percent: 75 }), 3);
  assert.equal(quality('completedEvaluation', {}, { percent: 120 }), 4);
});
test('uses valid positions of custom stages and competency grids, excludes unknown and singleton scales', () => {
  const snapshot = { evidenceTools: [{ id: 'tool', aspekte: [{ id: 'a', aspektDimensionen: [{ id: 'd', stufen: [{id:'low'},{id:'mid'},{id:'high'}] }, { id: 'single', stufen: [{id:'only'}] }] }] }] };
  const raw = { toolId: 'tool', selections: [{ aspectId: 'a', stages: [{ dimensionId: 'd', stageId: 'mid' }, {dimensionId:'single',stageId:'only'}] }] };
  assert.equal(quality('evidenceObservation', raw, {}, snapshot), 2);
  assert.equal(quality('evidenceObservation', { ...raw, toolId: 'missing' }, {}, snapshot), null);
  assert.equal(quality('completedEvaluation', { competencyResults: [{ columnId: 'high' }] }, { evaluationSheet: { type: 'kompetenzraster', competencyGrid: { columns: [{id:'low'},{id:'mid'},{id:'high'}] } } }), 4);
});
test('daily averaging prevents many entries on one day outweighing other days; change needs sufficient evidence', () => {
  const records = Array.from({ length: 10 }, () => ({ date: '2026-09-01', quality: 0, source: 'observation' }));
  records.push({ date: '2026-09-02', quality: 4, source: 'evaluation' }, { date: '2026-09-03', quality: null }, { date: '', quality: 4 });
  const result = feature.summarize(records);
  assert.equal(result.average, 2);
  assert.equal(result.daily.length, 2);
  assert.equal(result.scored.length, 11);
  assert.equal(result.change, null);
  assert.equal(feature.summarize([]).average, null);
  const trend = feature.summarize(Array.from({length:10}, (_,i) => ({ date: '2026-09-' + String(i+1).padStart(2,'0'), quality: i < 5 ? 1 : 3, source:'observation' })));
  assert.equal(trend.change, 2);
});
test('validates both grade scales, accepts zero points and retains historic schemes across edits and serialization', () => {
  const snapshot = { classes: [{ id:'c', gradingScheme:'grades', studentIds:['s'] }], students: [{id:'s'}] };
  const context = {classId:'c',studentId:'s'};
  const draft = {kind:'grade',date:'2026-09-20',grade:'2',note:'Begründung: Äöü'};
  const entry = feature.saveEntry(snapshot, context, draft, '2026-09-20T10:00Z', 'j1');
  assert.equal(entry.grade,2);
  assert.throws(() => feature.saveEntry(snapshot,context,{...draft,grade:'0'},'', 'bad'));
  assert.throws(() => feature.saveEntry(snapshot,context,{...draft,grade:''},'', 'bad'));
  assert.throws(() => feature.saveEntry(snapshot,{classId:'c',studentId:'other'},draft,'','bad'));
  assert.throws(() => feature.saveEntry(snapshot,context,{...draft,date:'2026-02-30'},'', 'bad'));
  snapshot.classes[0].gradingScheme = 'points';
  feature.saveEntry(snapshot,context,{...entry,grade:'3'},'2026-09-20T11:00Z','unused');
  assert.equal(snapshot.studentJournalEntries.length,1);
  assert.equal(snapshot.studentJournalEntries[0].gradingScheme,'grades');
  feature.saveEntry(snapshot,context,{...draft,grade:'0'},'2026-09-20T12:00Z','j2');
  feature.saveEntry(snapshot,context,{kind:'comment',date:'2026-09-20',note:'Ein freier Kommentar'},'2026-09-20T12:01Z','j3');
  const restored = ns.domain.serializeDomainSnapshot(ns.domain.createDomainSnapshot(snapshot));
  assert.equal(restored.classes[0].gradingScheme,'points');
  assert.equal(restored.studentJournalEntries[1].grade,0);
  assert.equal(restored.studentJournalEntries[0].gradingScheme,'grades');
  assert.equal(restored.studentJournalEntries[2].kind,'comment');
  assert.equal(restored.studentJournalEntries[2].grade,'');
  assert.throws(() => feature.saveEntry(snapshot,context,{kind:'comment',date:'2026-09-20',note:'   '},'','bad'));
  assert.equal(new ns.domain.SchoolClass({id:'old'}).gradingScheme,'grades');
});
test('renders escaped text, an empty state and complete timeline controls instead of a hard 14-record cap', () => {
  const controller = feature.createController({ escape:ns.shared.html.escapeHtml });
  const data = { snapshot:{}, student:{id:'s'}, studentName:'<script>bad()</script>', schoolClass:{id:'c',name:'7a'}, referenceDate:'2026-09-20', detailsHtml:'', records:[] };
  let html = controller.render(data);
  assert.match(html,/Noch keine bewertbaren Rückmeldungen/);
  assert.doesNotMatch(html,/<script>bad/);
  data.records = Array.from({length:45},(_,i)=>({ raw:{id:'r'+i,afb1:1}, type:'assessment',date:'2026-09-01', label:'Test',summary:'<img src=x>',sortKey:String(i) }));
  html = controller.render(data);
  assert.match(html,/Alle 45 anzeigen/);
  assert.match(html,/&lt;img/);
  assert.equal((html.match(/data-so-record=/g)||[]).length,34);
});
