(function () {
  const ns = window.Unterrichtsassistent;
  const m = ns.features.workspace.model;
  const esc = ns.shared.html.escapeHtml;
  const api = 'window.UnterrichtsassistentApp.workspace';
  const dateLabel = value => value ? new Date(value + 'T12:00:00').toLocaleDateString('de-DE', { weekday: 'short', day: 'numeric', month: 'short' }) : '';
  function button(label, action, attributes, primary) {
    return '<button type="button" class="ws-button' + (primary ? ' ws-button--primary' : ' ws-button--quiet') + '" ' + (attributes || '') + ' onclick="return ' + api + '.' + action + '">' + esc(label) + '</button>';
  }
  const empty = (title, text) => '<div class="ws-empty"><strong>' + esc(title) + '</strong><p>' + esc(text) + '</p></div>';
  ns.ui.views.overview = {
    id: 'overview', title: 'Übersicht',
    render(service) {
      const workspace = window.UnterrichtsassistentApp.workspace;
      if (!workspace) return '';
      const snapshot = service.snapshot, context = workspace.context(), date = context.date, range = workspace.getRange();
      const end = range === 'week' ? m.addDays(date, 6) : date;
      const allLessons = workspace.currentLessons();
      const lessons = allLessons.filter(item => item.lessonDate >= date && item.lessonDate <= end);
      const openTasks = m.list(snapshot.todos).filter(item => !item.done && item.taskStatus !== 'done');
      const dueTasks = openTasks.filter(item => item.dueDate && item.dueDate <= end).sort((a,b) => a.dueDate.localeCompare(b.dueDate));
      const waiting = openTasks.filter(item => item.taskStatus === 'waiting');
      const actions = m.list(snapshot.learningActions).filter(item => item.status !== 'reviewed' && item.status !== 'cancelled').sort((a,b) => String(a.dueDate).localeCompare(String(b.dueDate)));
      const dueActions = actions.filter(item => item.dueDate <= end);
      const overdue = dueTasks.filter(item => item.dueDate < date);
      const preparations = lessons.filter(lesson => {
        const plans = m.list(lesson.lessonPlanIds).map(id => m.list(snapshot.curriculumLessonPlans).find(plan => plan.id === id)).filter(Boolean);
        return !plans.length || plans.some(plan => plan.preparationTodoId && openTasks.some(task => task.id === plan.preparationTodoId));
      });
      const events = window.UnterrichtsassistentApp.getPlanningEventsForDisplay(snapshot, { rangeStart: date, rangeEnd: end }).filter(item => item.startDate <= end && (item.endDate || item.startDate) >= date).sort((a,b) => String(a.startDate).localeCompare(String(b.startDate)));
      const evaluations = m.list(snapshot.plannedEvaluations).filter(item => item.date >= date && item.date <= end);
      const recentReflections = m.list(snapshot.lessonReflections).slice().sort((a,b) => String(b.lessonDate).localeCompare(String(a.lessonDate))).slice(0, 4);
      const gaps = m.list(snapshot.knowledgeGapRecords).filter(item => !['resolved','closed','geschlossen'].includes(item.status) && !m.list(snapshot.learningActions).some(action => action.sourceId === item.id && action.status !== 'cancelled')).slice(-5).reverse();
      const lessonRows = lessons.flatMap(lesson => {
        const ids = m.list(lesson.lessonPlanIds);
        return ids.length > 1 ? ids.map((id,index) => Object.assign({}, lesson, { lessonPlanIds:[id], partLabel:' · Teil ' + (index + 1) + '/' + ids.length })) : [lesson];
      }).map(lesson => {
        const details = workspace.lessonDetails(lesson), plan = details.plan;
        const prep = plan && m.list(snapshot.todos).find(task => task.id === plan.preparationTodoId);
        const resources = m.list(snapshot.lessonResources).filter(item => item.lessonPlanId === details.planId);
        const outstanding = resources.filter(item => item.status !== 'ready').length;
        const reflection = m.list(snapshot.lessonReflections).find(item => item.classId === lesson.classId && item.lessonDate === lesson.lessonDate && item.lessonId === lesson.id && item.lessonPlanId === details.planId);
        const attrs = 'data-class="' + esc(lesson.classId) + '" data-date="' + esc(lesson.lessonDate) + '" data-time="' + esc(lesson.startTime || '') + '" data-plan="' + esc(details.planId) + '" data-lesson="' + esc(lesson.id) + '"';
        return '<article class="ws-lesson"><div class="ws-lesson__time"><strong>' + esc(lesson.startTime || 'Zeit offen') + '</strong><span>' + esc(range === 'week' ? dateLabel(lesson.lessonDate) : lesson.endTime || 'Zusatzstunde') + '</span></div><div class="ws-lesson__body"><p class="ws-eyebrow">' + esc(m.className(snapshot, lesson.classId)) + esc(lesson.partLabel || '') + (lesson.room ? ' · ' + esc(lesson.room) : '') + '</p><h3>' + esc(details.topic) + '</h3><div class="ws-tags"><span class="ws-tag' + (!plan ? ' ws-tag--attention' : '') + '">' + (plan ? 'Ablauf geplant' : 'Planung offen') + '</span>' + (prep ? '<button type="button" class="ws-tag' + (!prep.done ? ' ws-tag--attention' : '') + '" data-id="' + esc(prep.id) + '" onclick="' + api + '.openTask(this.dataset.id)">' + (prep.done ? 'Vorbereitung erledigt' : 'Vorbereitung offen') + '</button>' : '') + (outstanding ? '<span class="ws-tag ws-tag--attention">' + outstanding + ' Material noch vorbereiten</span>' : '') + (reflection ? '<span class="ws-tag ws-tag--success">Abschluss erfasst</span>' : '') + '</div></div><div class="ws-lesson__actions">' + button('Unterricht öffnen', 'openLesson(this.dataset.class,this.dataset.date,this.dataset.time,this.dataset.plan,\'live\')', attrs, true) + (plan ? button('Planung', 'openLesson(this.dataset.class,this.dataset.date,this.dataset.time,this.dataset.plan,\'plan\')', attrs) + button('Material', 'openResources(this.dataset.plan,this.dataset.class)', attrs) : button('Planen', 'openLesson(this.dataset.class,this.dataset.date,this.dataset.time,\'\',\'plan\')', attrs)) + (lesson.lessonDate <= date ? button(reflection ? 'Rückblick öffnen' : 'Abschließen', 'openReflection(this.dataset.class,this.dataset.date,this.dataset.lesson,this.dataset.plan)', attrs) : '') + '</div></article>';
      }).join('');
      const taskRows = dueTasks.slice(0, 8).map(task => '<button type="button" class="ws-list-row" data-id="' + esc(task.id) + '" onclick="' + api + '.openTask(this.dataset.id)"><span class="ws-task-dot' + (task.dueDate < date ? ' is-overdue' : '') + '"></span><span><strong>' + esc(task.title) + '</strong><small>' + esc(task.relatedClassId ? m.className(snapshot, task.relatedClassId) : task.category || 'Allgemein') + '</small></span><span class="ws-due' + (task.dueDate < date ? ' is-overdue' : '') + '">' + esc(task.dueDate < date ? 'Überfällig · ' + dateLabel(task.dueDate) : dateLabel(task.dueDate)) + '</span></button>').join('');
      const actionRows = actions.slice(0, 6).map(action => '<div class="ws-action-row"><div><span class="ws-eyebrow">' + esc(m.studentName(snapshot, action.studentId) || m.className(snapshot, action.classId)) + '</span><strong>' + esc(action.title) + '</strong><p>' + esc(action.sourceText || 'Geplanter nächster Lernschritt') + '</p><small>Überprüfung: ' + esc(dateLabel(action.dueDate)) + '</small></div>' + button('Wirkung prüfen', 'openReview(this.dataset.id)', 'data-id="' + esc(action.id) + '"', action.dueDate <= end) + '</div>').join('');
      const completedActions = m.list(snapshot.learningActions).filter(item => item.status === 'reviewed' || item.status === 'cancelled').slice(-5).reverse();
      return '<div class="ws-overview"><section class="ws-welcome"><div><p class="ws-eyebrow">Dein Arbeitsplatz</p><h2>' + (range === 'week' ? 'Die nächsten Tage im Blick.' : 'Ein klarer Blick auf deinen Tag.') + '</h2><p>' + esc(dateLabel(date)) + (range === 'week' ? ' – ' + esc(dateLabel(end)) : '') + ' · ' + lessons.length + ' Unterrichtsblöcke' + (context.manual ? ' · Gewähltes Datum' : '') + '</p></div><div class="ws-welcome__actions"><div class="ws-segment" role="group" aria-label="Zeitraum">' + '<button type="button" aria-pressed="' + (range === 'today') + '" onclick="' + api + '.setRange(\'today\')">Tag</button><button type="button" aria-pressed="' + (range === 'week') + '" onclick="' + api + '.setRange(\'week\')">7 Tage</button></div>' + button('+ Schnell erfassen','openQuick()', '', true) + '</div></section>'
        + '<section class="ws-stats" aria-label="Aufmerksamkeit"><a href="#overviewLessons" class="ws-stat"><span>Unterricht</span><strong>' + lessons.length + '</strong><small>' + preparations.length + ' mit offener Planung / Vorbereitung</small></a><a href="#overviewTasks" class="ws-stat"><span>Fällige Aufgaben</span><strong>' + dueTasks.length + '</strong><small>' + overdue.length + ' davon überfällig</small></a><a href="#overviewFollowUps" class="ws-stat"><span>Wirkung überprüfen</span><strong>' + dueActions.length + '</strong><small>Beobachtung mit nächstem Schritt</small></a><a href="#overviewWaiting" class="ws-stat"><span>Rückmeldungen</span><strong>' + waiting.length + '</strong><small>Aufgaben im Wartestatus</small></a></section>'
        + (!m.list(snapshot.classes).length ? '<section class="ws-panel ws-onboarding"><h3>Deinen Arbeitsplatz einrichten</h3><p>Lege zuerst eine Lerngruppe und deinen Stundenplan an. Deine Stunden und Aufgaben laufen anschließend hier zusammen.</p>' + button('Lerngruppe anlegen', 'openView(\'klasse\')','',true) + ' ' + button('Stundenplan einrichten','openView(\'stundenplan\')') + '</section>' : '')
        + '<div class="ws-columns"><div class="ws-main-column"><section class="ws-panel" id="overviewLessons"><header class="ws-panel__heading"><div><span class="ws-eyebrow">Planen · Unterrichten · Nachbereiten</span><h3>Dein Unterricht</h3></div>' + button('Stundenplan','openView(\'stundenplan\')') + '</header>' + (lessonRows || empty('Hier ist gerade unterrichtsfrei.', 'Wechsle zu „7 Tage“ oder wähle links ein anderes Datum.')) + '</section>'
        + '<section class="ws-panel" id="overviewFollowUps"><header class="ws-panel__heading"><div><span class="ws-eyebrow">Vom Beobachten zum Handeln</span><h3>Nächste Lernschritte</h3></div>' + button('+ Maßnahme','openAction()') + '</header>' + (actionRows || empty('Noch keine offenen Maßnahmen.', 'Halte eine konkrete Übung oder Unterstützung fest und prüfe später, was sie bewirkt hat.')) + (gaps.length ? '<details class="ws-gaps"><summary>Aus Beobachtungen aufgreifen · ' + gaps.length + '</summary>' + gaps.map(gap => '<div class="ws-action-row"><div><strong>' + esc(gap.content) + '</strong><small>' + esc(m.studentName(snapshot, gap.studentId)) + ' · ' + esc(m.className(snapshot, gap.classId)) + '</small></div>' + button('Maßnahme planen','openAction(this.dataset.id)', 'data-id="' + esc(gap.id) + '"') + '</div>').join('') + '</details>' : '') + (completedActions.length ? '<details class="ws-gaps"><summary>Abgeschlossene Maßnahmen</summary>' + completedActions.map(action => '<div class="ws-action-row"><div><strong>' + esc(action.title) + '</strong><p>' + esc(action.status === 'cancelled' ? 'Abgebrochen · ' + (action.cancellationReason || 'Keine Wirkungsüberprüfung') : action.outcome) + '</p></div>' + button('Verlauf', 'openReview(this.dataset.id)', 'data-id="' + esc(action.id) + '"') + '</div>').join('') + '</details>' : '') + '</section></div>'
        + '<aside class="ws-side-column"><section class="ws-panel" id="overviewTasks"><header class="ws-panel__heading"><h3>Was ansteht</h3>' + button('Alle Aufgaben','openView(\'todos\')') + '</header>' + (taskRows || empty('Keine fälligen Aufgaben.', 'Neue Aufgaben lassen sich oben schnell erfassen.')) + (dueTasks.length > 8 ? '<p class="ws-muted">Weitere ' + (dueTasks.length - 8) + ' Aufgaben in der Aufgabenübersicht.</p>' : '') + '</section>'
        + '<section class="ws-panel" id="overviewWaiting"><header class="ws-panel__heading"><h3>Ausstehende Rückmeldungen</h3></header>' + (waiting.slice(0, 4).map(task => '<button class="ws-list-row" type="button" data-id="' + esc(task.id) + '" onclick="' + api + '.openTask(this.dataset.id)"><span><strong>' + esc(task.title) + '</strong><small>' + esc((m.list(snapshot.taskPeople).find(person => person.id === task.waitingForPersonId) || {}).name || 'Rückmeldung offen') + (task.waitingSince ? ' · seit ' + esc(dateLabel(task.waitingSince.slice(0,10))) : '') + '</small></span><span aria-hidden="true">↗</span></button>').join('') || '<p class="ws-muted">Aktuell keine Aufgaben im Wartestatus.</p>') + '</section>'
        + '<section class="ws-panel"><header class="ws-panel__heading"><h3>Termine & Bewertungen</h3>' + button('Kalender','openView(\'planung\')') + '</header>' + (events.slice(0,5).map(item => '<div class="ws-event"><span>' + esc(dateLabel(item.startDate)) + '</span><strong>' + esc(item.title) + '</strong></div>').join('') || '<p class="ws-muted">Keine weiteren Termine im Zeitraum.</p>') + (evaluations.length ? '<p class="ws-muted">' + evaluations.length + ' geplante Bewertung(en) im Zeitraum.</p>' + button('Bewertungen öffnen','openView(\'bewertung\')') : '') + '</section>'
        + (recentReflections.length ? '<section class="ws-panel"><header class="ws-panel__heading"><h3>Letzte Stundenabschlüsse</h3></header>' + recentReflections.map(entry => '<button class="ws-list-row" type="button" data-class="' + esc(entry.classId) + '" data-date="' + esc(entry.lessonDate) + '" data-lesson="' + esc(entry.lessonId) + '" data-plan="' + esc(entry.lessonPlanId) + '" onclick="' + api + '.openReflection(this.dataset.class,this.dataset.date,this.dataset.lesson,this.dataset.plan)"><span><strong>' + esc(entry.topic || m.className(snapshot, entry.classId)) + '</strong><small>' + esc(dateLabel(entry.lessonDate)) + ' · ' + esc(entry.summary || entry.remaining) + '</small></span></button>').join('') + '</section>' : '')
        + '</aside></div></div>';
    }
  };
}());
